/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdCaretRight: typeof import('@kalimahapps/vue-icons/ad')['AdCaretRight']
    AiCourseraSquare: typeof import('@kalimahapps/vue-icons/ai')['AiCourseraSquare']
    AiCrossrefSquare: typeof import('@kalimahapps/vue-icons/ai')['AiCrossrefSquare']
    AkHomeAlt1: typeof import('@kalimahapps/vue-icons/ak')['AkHomeAlt1']
    BsCalendar4Range: typeof import('@kalimahapps/vue-icons/bs')['BsCalendar4Range']
    BsListTask: typeof import('@kalimahapps/vue-icons/bs')['BsListTask']
    BxDetail: typeof import('@kalimahapps/vue-icons/bx')['BxDetail']
    BxSolidEditAlt: typeof import('@kalimahapps/vue-icons/bx')['BxSolidEditAlt']
    CaSettings: typeof import('@kalimahapps/vue-icons/ca')['CaSettings']
    CaVirtualMachine: typeof import('@kalimahapps/vue-icons/ca')['CaVirtualMachine']
    CaVolumeBlockStorage: typeof import('@kalimahapps/vue-icons/ca')['CaVolumeBlockStorage']
    ChPlus: typeof import('@kalimahapps/vue-icons/ch')['ChPlus']
    CoAddPlus: typeof import('@kalimahapps/vue-icons/co')['CoAddPlus']
    DataSource: typeof import('./src/components/DataSource.vue')['default']
    DataSourceTypeIcon: typeof import('./src/components/DataSourceTypeIcon.vue')['default']
    DeMongodbOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DeMongodbOriginalWordmark']
    DeMysqlOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DeMysqlOriginalWordmark']
    DePostgresqlOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DePostgresqlOriginalWordmark']
    DeRedisOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DeRedisOriginalWordmark']
    FeDatabase: typeof import('@kalimahapps/vue-icons/fe')['FeDatabase']
    FlFilledAdd: typeof import('@kalimahapps/vue-icons/fl')['FlFilledAdd']
    GlTaskDone: typeof import('@kalimahapps/vue-icons/gl')['GlTaskDone']
    ReDatabase2Line: typeof import('@kalimahapps/vue-icons/re')['ReDatabase2Line']
    ReDeleteBin7Line: typeof import('@kalimahapps/vue-icons/re')['ReDeleteBin7Line']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/SidebarNav.vue')['default']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    TiOutlineCloudStorage: typeof import('@kalimahapps/vue-icons/ti')['TiOutlineCloudStorage']
  }
}
