/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AkGithubFill: typeof import('@kalimahapps/vue-icons/ak')['AkGithubFill']
    AkHomeAlt1: typeof import('@kalimahapps/vue-icons/ak')['AkHomeAlt1']
    AkPlay: typeof import('@kalimahapps/vue-icons/ak')['AkPlay']
    BsListTask: typeof import('@kalimahapps/vue-icons/bs')['BsListTask']
    BxSolidEditAlt: typeof import('@kalimahapps/vue-icons/bx')['BxSolidEditAlt']
    CaVirtualMachine: typeof import('@kalimahapps/vue-icons/ca')['CaVirtualMachine']
    CaVolumeBlockStorage: typeof import('@kalimahapps/vue-icons/ca')['CaVolumeBlockStorage']
    ChPlus: typeof import('@kalimahapps/vue-icons/ch')['ChPlus']
    CoMoon: typeof import('@kalimahapps/vue-icons/co')['CoMoon']
    ConfirmModal: typeof import('./src/components/ConfirmModal.vue')['default']
    DataSourceTypeIcon: typeof import('./src/components/datasource/DataSourceTypeIcon.vue')['default']
    DeMysqlOriginal: typeof import('@kalimahapps/vue-icons/de')['DeMysqlOriginal']
    DeMysqlOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DeMysqlOriginalWordmark']
    DePostgresqlOriginal: typeof import('@kalimahapps/vue-icons/de')['DePostgresqlOriginal']
    DePostgresqlOriginalWordmark: typeof import('@kalimahapps/vue-icons/de')['DePostgresqlOriginalWordmark']
    FaBandsAws: typeof import('@kalimahapps/vue-icons/fa')['FaBandsAws']
    FeDatabase: typeof import('@kalimahapps/vue-icons/fe')['FeDatabase']
    GlCollapseLeft: typeof import('@kalimahapps/vue-icons/gl')['GlCollapseLeft']
    GlTaskDone: typeof import('@kalimahapps/vue-icons/gl')['GlTaskDone']
    HiLanguage: typeof import('@kalimahapps/vue-icons/hi')['HiLanguage']
    LocalOptions: typeof import('./src/components/datasource/LocalOptions.vue')['default']
    MdOutlinedWbSunny: typeof import('@kalimahapps/vue-icons/md')['MdOutlinedWbSunny']
    MdTwotoneRestore: typeof import('@kalimahapps/vue-icons/md')['MdTwotoneRestore']
    MySQLOptions: typeof import('./src/components/datasource/MySQLOptions.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostgreSQLOptions: typeof import('./src/components/datasource/PostgreSQLOptions.vue')['default']
    ReDeleteBin7Line: typeof import('@kalimahapps/vue-icons/re')['ReDeleteBin7Line']
    RestoreLocalOptions: typeof import('./src/components/restore/RestoreLocalOptions.vue')['default']
    RestoreMySQLOptions: typeof import('./src/components/restore/RestoreMySQLOptions.vue')['default']
    RestorePostgreSQLOptions: typeof import('./src/components/restore/RestorePostgreSQLOptions.vue')['default']
    RestoreSSHOptions: typeof import('./src/components/restore/RestoreSSHOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
    SSHOptions: typeof import('./src/components/datasource/SSHOptions.vue')['default']
    StorageS3Options: typeof import('./src/components/storage/StorageS3Options.vue')['default']
    StorageSSHOptions: typeof import('./src/components/storage/StorageSSHOptions.vue')['default']
    StorageTypeIcon: typeof import('./src/components/storage/StorageTypeIcon.vue')['default']
    TaskStatus: typeof import('./src/components/TaskStatus.vue')['default']
    TiOutlineCloudStorage: typeof import('@kalimahapps/vue-icons/ti')['TiOutlineCloudStorage']
  }
}
