name: deploy
on: [ push ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: Install npm dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: "-rlgoDzvc -i --delete"
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/root/docker/caddy/www/databack-web-pro"
          SOURCE: "dist/"
